[package]
name = "mithril"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.0"
tract = "0.20.7"
tract-onnx = "0.20.7"
